### ISSUE TITLE
Tests fail when building outside of source 

### ISSUE THREAD

**Issue by dengert** [latchset/pkcs11-provider#109]
**Describe the bug**
git HEAD is  47e1c475a4f6da14f7028208514ee888b3db305a
When configuring in a build directory (build) outside of the  source directory `make check` fails:
```
doug@XU-22:/a/appl/pkcs11-provider-git/build$ make check
Making check in src
make[1]: Entering directory '/a/appl/pkcs11-provider-git/build/src'
make[1]: Leaving directory '/a/appl/pkcs11-provider-git/build/src'
Making check in tests
make[1]: Entering directory '/a/appl/pkcs11-provider-git/build/tests'
make  tsession tgenkey ttls tdigests \
  helpers.sh setup-softhsm.sh setup-softokn.sh softhsm-proxy.sh test-wrapper tbasic teccsha2 thkdf toaepsha2 trsapss
make[2]: Entering directory '/a/appl/pkcs11-provider-git/build/tests'
make[2]: 'tsession' is up to date.
make[2]: 'tgenkey' is up to date.
make[2]: 'ttls' is up to date.
make[2]: 'tdigests' is up to date.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/helpers.sh'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/setup-softhsm.sh'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/setup-softokn.sh'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/softhsm-proxy.sh'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/test-wrapper'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/tbasic'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/teccsha2'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/thkdf'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/toaepsha2'.
make[2]: Nothing to be done for '../../pkcs11-provider/tests/trsapss'.
make[2]: Leaving directory '/a/appl/pkcs11-provider-git/build/tests'
make  check-TESTS
make[2]: Entering directory '/a/appl/pkcs11-provider-git/build/tests'
make[3]: Entering directory '/a/appl/pkcs11-provider-git/build/tests'
SKIP: basic-softokn
SKIP: basic-softhsm-proxy
SKIP: eccsha2-softokn
SKIP: oaepsha2-softokn
SKIP: hkdf-softokn
SKIP: rsapss-softokn
SKIP: digests-softokn
SKIP: digests-softhsm-proxy
SKIP: genkey-softokn
SKIP: genkey-softhsm
SKIP: session-softokn
SKIP: session-softhsm-proxy
SKIP: tls-softokn
SKIP: tls-softhsm-proxy
============================================================================
Testsuite summary for pkcs11-provider 0.1
============================================================================
# TOTAL: 14
# PASS:  0
# SKIP:  14
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

**To Reproduce**

1. cd to git source (in my case: /a/appl/pkcs11-provider-git/pkcs11-provider)
2. autoreconf -fi
3. cd ..
4. mkdir build
5. cd build
6. ../pkcs11-provider/configure  
7. make
8. make check

**Expected behavior**
make check works when building in the source but not when built outside the source

**Operating environment (please complete the following information):**
 - OS: XUbuntu
 - Version 22.10

**Additional context**

Adding `set -xv` to `test`wrapper` failure to source `testvars` shows each test fails with 77 like this one:
```
TEST_PARAMS=(${1//-/ })
+ TEST_PARAMS=(${1//-/ })

TEST_NAME=$(basename ${TEST_PARAMS[0]})
++ basename ../../pkcs11
+ TEST_NAME=pkcs11
TEST_PATH=$(dirname ${TEST_PARAMS[0]})
++ dirname ../../pkcs11
+ TEST_PATH=../..
TOKEN_DRIVER=${TEST_PARAMS[1]}
+ TOKEN_DRIVER=provider/tests/basic

if [ -f "./tmp.${TOKEN_DRIVER}/testvars" ];  then
    source ./tmp.${TOKEN_DRIVER}/testvars
else
    exit 77 # token not configured, skip
fi
+ '[' -f ./tmp.provider/tests/basic/testvars ']'
+ exit 77
SKIP basic-softokn (exit status: 77)
```

**Comment by simo5** [comment]
make distcheck, which uses out of tree build, works, so I wonder what is going on here...

**Comment by simo5** [comment]
I can't reproduce in Fedora, I made the same steps and make check works fine

**Comment by simo5** [comment]
wait there is a very odd expansion going on here: ./tmp.provider/tests/basic/testvars ?
that should be ./tmp.softokn/testvars

what version of make are you using?
Is it not GNU make ?

**Comment by simo5** [comment]
also what version of autoconf/automake ?
can you attach the generated tests/Makefile ?

**Comment by dengert** [comment]
All the packages are from XUbuntu-22.10 installed as a VM this last week  just to test pkcs11-provider. 

I fetched and merged from "url = https://github.com/latchset/pkcs11-provider.git"  this morning

$ openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)

$ automake --version
automake (GNU automake) 1.16.5 which was installed as a VM last week to simplify testing. 

/usr/bin/autoconf --version
autoconf (GNU Autoconf) 2.71

$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu

$ gcc --version
gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0


[test-Makefile.txt](https://github.com/latchset/pkcs11-provider/files/10043412/test-Makefile.txt)

**Comment by dengert** [comment]
The in source `autoreconf -fi, ./configure, make, make check` was working yesterday. But now it does:
 ```
==============test-suite.log=================================
   pkcs11-provider 0.1: tests/test-suite.log
===============================================

# TOTAL: 14
# PASS:  1
# SKIP:  1
# XFAIL: 0
# FAIL:  12
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: basic-softokn
===================

test-suite.logExecuting ./tbasic

## Export Public key to a file
openssl pkey -in $BASEURI -pubin -pubout -out ${TSTOUT}.pub
Could not open file or uri for loading public key of Public Key from pkcs11:id=%69%d3%3f%7f%9b%ec%f0%5b%14%69%0d%73%8e%70%45%63%ad%2f%a5%3c
40675C0BE17F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file
40675C0BE17F0000:error:80000002:system library:file_open:No such file or directory:../providers/implementations/storemgmt/file_store.c:267:calling stat(pkcs11:id=%69%d3%3f%7f%9b%ec%f0%5b%14%69%0d%73%8e%70%45%63%ad%2f%a5%3c)
40675C0BE17F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=pkcs11
40675C0BE17F0000:error:1608010C:STORE routines:inner_loader_fetch:unsupported:../crypto/store/store_meth.c:383:No store loader found. For standard store loaders you need at least one of the default or base providers available. Did you forget to load them? Info: Global default library context, Scheme (pkcs11 : 0), Properties (<null>)
FAIL basic-softokn (exit status: 1)

FAIL: basic-softhsm-proxy

(and many other similar failures)
```

**Comment by simo5** [comment]
The error you are getting locally just means the provider is not being properly loaded for some reason.
It may be a detection error finding the modules, can you attach the openssl.cnf file for the softokn test? (in tests/tmp.softokn/openssl.cnf)

**Comment by dengert** [comment]
Here is the `a/appl/pkcs11-provider-git/pkcs11-provider/tests/tmp.softokn/openssl.cnf` from the insource build

[pkcs11-provider-tests-tmp.softokn-openssl.cnf.txt](https://github.com/latchset/pkcs11-provider/files/10044232/pkcs11-provider-tests-tmp.softokn-openssl.cnf.txt)

`/a/appl/pkcs11-provider-git/pkcs11-provider/tests/pinfile.txt` is not present

```
doug@XU-22:~ ls -l /a/appl/pkcs11-provider-git/pkcs11-provider/src/.libs/pkcs11_provider.so
-rwxrwxr-x 1 doug doug 637560 Nov 18 11:34 /a/appl/pkcs11-provider-git/pkcs11-provider/src/.libs/pkcs11_provider.so
doug@XU-22:~$ ldd /a/appl/pkcs11-provider-git/pkcs11-provider/src/.libs/pkcs11_provider.so
	linux-vdso.so.1 (0x00007ffcd5a5a000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fad7a400000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fad7a000000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fad7a8de000)
doug@XU-22:~$ ls -l /a/appl/pkcs11-provider-git/pkcs11-provider/tests/tmp.softokn/tokens
total 104
-rw------- 1 doug doug 36864 Nov 17 11:20 cert9.db
-rw------- 1 doug doug 61440 Nov 17 11:20 key4.db
-rw------- 1 doug doug   425 Nov 17 11:20 pkcs11.txt
doug@XU-22:~$ ls -l /a/appl/pkcs11-provider-git/pkcs11-provider/tests/pinfile.txt
ls: cannot access '/a/appl/pkcs11-provider-git/pkcs11-provider/tests/pinfile.txt': No such file or directory
```

**Comment by simo5** [comment]
was this a clean tree?
the pinfile.txt file is generated by setup-<driver>.sh (they both do it, arguably a bug or we should move the file in the per driver directory, but both set the same value so not a real issue.

Do you have setup-softoken.log ?
Any error in there?

**Comment by simo5** [comment]
As for the original error I do not see setup-soft*.sh scripts called at all ... perhaps run make -d [dist]check so that you get debugging output from make and hopefully see where it goes wrong

**Comment by dengert** [comment]
This issue only occurred when running `make check`  PR #111 fixes several problems and now  `make check`  runs all 14 checks and all PASS when built in the source directory or some other directory.

**Comment by simo5** [comment]
Yeah great catch on that '-' issue ... just a few minor tweaks and I'll merge it
