### ISSUE TITLE
configure: WARNING: The p11-kit client not found. Can not run SoftHSM tests

### ISSUE THREAD

**Issue by gilweis** [latchset/pkcs11-provider#110]
**Describe the bug**
configure: WARNING: The p11-kit client not found. Can not run SoftHSM tests

**To Reproduce**
./configure

**Expected behavior**

**Operating environment (please complete the following information):**
 - OS: [Ununtu 22.10]

**Additional context**
$ softhsm2-util --version
2.6.1

**Comment by simo5** [comment]
do you have p11-kit libp11-kit-dev p11-kit-modules installed ?

**Comment by gilweis** [comment]
I have:
p11-kit, p11-kit-modules.
Why libp11-kit-dev is needed for testing softhsm?

**Comment by gilweis** [comment]
Thanks,
Now it's working.
