### ISSUE TITLE
ECDSA signatures are generated/verified wrong

### ISSUE THREAD

**Issue by fabled** [latchset/pkcs11-provider#123]
OpenSSL wants DER encoded ECDSASignature, but PKCS#11 uses RAW byte sequences.

See PR #121 for a test case.

**Comment by dengert** [comment]
OPenSC uses: sc_asn1_sig_value_rs_to_sequence  https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/asn1.c#L2146

Note it drops leading zeros in r an s.

**Comment by fabled** [comment]
Yes, there are "hidden" rules on how to do the conversion. Also one leading zero is needed in DER encoding if the first octet is `>= 0x80` because it's an integer encoding (not octet string) and the numbers are unsigned.

Since this is openssl plugin, we could create `ECDSA_SIG` and use `i2d_ECDSA_SIG` etc. Though that may involve quite a bit of dynamic allocations. Wondering if it's better to do handrolled encoder, or use something in openssl.
