### ISSUE TITLE
URI matching issues

### ISSUE THREAD

**Issue by Jakuje** [latchset/pkcs11-provider#124]
**Describe the bug**
When parsing parts of the PKCS#11 URI, the function `parse_attr()` allocates just the `len + 1` bytes for the members (for example `uri->object`, but when these are compared against the token data, the hardcoded length from the PKCS#11 specification (32B) is used in `p11prov_uri_match_token()`. This leads to the buffer overruns (probably not reported because the openssl's allocs are used) and failures to match the keys.

**To Reproduce**
1. Try to select key by URI
2. See the matching failed

**Expected behavior**
Matching works

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version 36

**Token and application used (please complete the following information):**
 - Device: SoftHSM, p11-kit
 - PKCS11 Driver version: latest
 - Application libssh
 - Version master

**Additional context**
The `parse_attr` either needs to allocate the full length of the buffers it is checked against in `p11prov_uri_match_token()` or the `p11prov_uri_match_token()` needs to be adjusted to not compare behind the end of the buffer, ignoring trailing whitespace.

**Comment by fabled** [comment]
This was fixed with #119 and can be closed?

**Comment by Jakuje** [comment]
> This was fixed with #119 and can be closed?

Right. Took me too long to report the issue until you fixed that.
