### ISSUE TITLE
Add support for getting public key from a certificate object

### ISSUE THREAD

**Issue by simo5** [latchset/pkcs11-provider#127]
We have fallback code to load an associated public key from a private key object.
We need to extend this to also try to use a certificate object if a public key object is not available as some tokens store only certificate and private key and depend on software to retrieve the public key from the certificate.

**Comment by dengert** [comment]
Depends on the pkcs11 module too. PIV for example, needs to read the certificate to find the public key from the SPKI to get key type size and curve. OpenSC  PIV driver makes the public key available to pkcs11 caller.

**Comment by simo5** [comment]
It doesn't really matter to the provider code, which will take attributes, if present, even directly from the private key.
This bug is about trying to fallback if the public attributes are not present.

**Comment by dengert** [comment]
It maybe low priority as any good module would do it.

**Comment by simo5** [comment]
I assume by modules here you mean pkcs11 drivers?

**Comment by dengert** [comment]
Yes the modules that implement pkcs11 like opensc-pkcs11.so. Although it might be on card driver basis. 

It looks rather easy to get the pubkey from the certificate using `EVP_PKEY *X509_get_pubkey(X509 *x);` Given that CKO_CERTIFICATE ,  CKO_PUBLIC_KEY, CKO_PRIVATE_KEY  should have the same CKA_ID,  CKO_CERTIFICATE->CKA_VALUE is the ASN.1 encoded certificate.

**Comment by simo5** [comment]
The main issue seems how to test this, because, at least NSS generates a public key object even if only a private key and a certificate are provided for import.

For now I am manually testing with a modification that makes the fallback code ignore the public key object ...

**Comment by selvanair** [comment]
This fallback to using certificate does not seem to work when an EC private key is passed to SSL_CTX_use_Privatekey() even if matching certificate is present with same ID. In this case `p11prov_ec_match()` gets called which fails to find the public key via `find_associated_obj()`. Would be nice to get the fallback applied here too for wider usability.

Tested using a soft token (softhsm2) where only private key and certificate were imported into the token using `p11tool`. The same token works with `pkcs11-helper` library. Unlike `p11tool`, `softhsm2-util` imports keypair in one step and creates both public and private key objects in the token --- in that case there are no such errors, obviously.
