### ISSUE TITLE
Provide .clang-format

### ISSUE THREAD

**Issue by oerdnj** [latchset/pkcs11-provider#14]
Hey,

before, I start doing this (it will require some tweaking), we had great success with adding and using `.clang-format` to reformat files automatically. I can try to model the `.clang-format` according to the current code (or just use `linux` format). But before I do that, is this something you would be willing to accept?  There are numerous plugins to editors to format on save and it makes the life much easier in the end.

**Comment by simo5** [comment]
Do you have an example?
I definitely do not like the Linux kernel style eats too much screen estate for no reason and they laso have other dubious practices.
