### ISSUE TITLE
When searching for slot to generate keys consult the mechanisms

### ISSUE THREAD

**Issue by beldmit** [latchset/pkcs11-provider#140]
**Describe the feature**
We should not try to generate new keys using a particular slot if it doesn't support the necessary mechanism.

**Comment by simo5** [comment]
This looks like a duplicate of #139 effectively, in general both #139 #140 ask to check that the slot support the desired mechanism for the operation we need to complete.

**Comment by beldmit** [comment]
I agree, any of them can be closed.

**Comment by simo5** [comment]
Duplicate of #139
