### ISSUE TITLE
EC+digest signatures should fall back to raw EC signatures if the specific mechanism is not supported

### ISSUE THREAD

**Issue by Jakuje** [latchset/pkcs11-provider#168]
**Describe the bug**
The SoftHSM supports only `CKM_ECDSA` mechanism, which is raw EC signature. The pkcs11-provider fails when we try to create hashed signature using any digest+signature fails with the following logs:
```
[interface.gen.c:291] p11prov_CopyObject(): Calling C_CopyObject
[objects.c:168] cache_key(): Key 17:25 cached as 27:27
[signature.c:1630] p11prov_ecdsa_set_ctx_params(): ecdsa set ctx params (ctx=0x2164b50, params=(nil))
[signature.c:1454] p11prov_ecdsa_digest_sign_update(): ecdsa digest sign update (ctx=0x2164b50, data=0x451f00, datalen=65)
[interface.gen.c:153] p11prov_GetMechanismInfo(): Calling C_GetMechanismInfo
[interface.gen.c:157] p11prov_GetMechanismInfo(): Error: 0x00000070; Error returned by C_GetMechanismInfo
C_GetMechanismInfo for CKM_ECDSA_SHA512(4166) failed 112
```
The provider should fall back to the `CKM_ECDSA` if the `CKM_ECDSA_SHA*` mechanism is not available by doing the digest inside OpenSSL. This might be problematic with the certifications, but it should improve the imteroperability with mode pkcs11 providers or smart cards.

**To Reproduce**
1. Go to https://gitlab.com/libssh/libssh-mirror/-/merge_requests/334
2. See the latest failed pipeline results

**Expected behavior**
The signatures using ECDSA keys work with CKM_ECDSA mechanism only.

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version 36

**Token and application used (please complete the following information):**
 - Device: SoftHSM
 - PKCS11 Driver version: 2.6.1
 - Application: libssh
 - Version: master

**Additional context**
This should also allow us enabling the ecdsa signature tests with softhsm pipeline. The following change:
```
diff --git a/tests/Makefile.am b/tests/Makefile.am
index c3c58aa..87fae4d 100644
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -46,7 +46,7 @@ dist_check_SCRIPTS = \
 test_LIST = \
 	basic-softokn basic-softhsm-proxy \
 	certs-softokn certs-softhsm-proxy \
-	eccsha2-softokn \
+	eccsha2-softokn eccsha2-softhsm-proxy \
 	oaepsha2-softokn \
 	hkdf-softokn \
 	rsapss-softokn \
```
Now gives the same error here:
```
Error signing raw input data                                                     
Public Key operation error                                                       
804B32944F7F0000:error:40800070:pkcs11:p11prov_GetMechanismInfo:An invalid mechanism was specified to the cryptographic operation:interface.gen.c:157:Error returned by C_GetMechanismInfo
804B32944F7F0000:error:40800001:pkcs11:p11prov_sig_operate_init:reason(1):signature.c:605:Failed to open session on slot 17
```

**Comment by simo5** [comment]
Step 1 is to use the fact we already know which mechanisms are supported to detect as soon as a hashed signature is requested that we do not support it.

Then we can build fallback code in that case.

**Comment by beldmit** [comment]
If I correctly understand, implicit fallback is not a good solution from the certification point of view

**Comment by simo5** [comment]
We can make fallback configurable.
Unfortunately OpenSSL considers the whole signature provider as available or not so we need to either return an error or fallback I am afraid

**Comment by simo5** [comment]
I checked the code a bit and I was hoping we could just avoid returning the digest_sign_* functions in the provider to let openssl do the fall-backing ... but that's not how it works, the fallback needs to be implemented in the provider.

Given the signing code is common between all signature cases I need to think where to inject the fallback code ...
