### ISSUE TITLE
Implement software fallback from PSS to raw RSA signatures or return errors early

### ISSUE THREAD

**Issue by simo5** [latchset/pkcs11-provider#194]
**Describe the feature**
OpenSSL does separate keymgmt for RSA vs RSA-PSS "keys" (which is not even a thing in pkcs#11), but implements a single provider for RSA signatures, and assumes both PKCS!.5 and PSS signatures are always doable ...

**Expected behavior**
Given OpenSSL does not understand that a provider may be able to perform PKCS signatures, but not PSS signatures, we need to implement software fallback if a token support RSA raw signatures.

**Additional context**
It may be ok to return an error as soon as a PSS padding mode is set via rsasig_set_ctx_params instead of performing ful emulation.

**Comment by dengert** [comment]
I would say this is very low priority. 

The pkcs11 **module** opensc-pkcs11.so (and any good pkcs11 **module**) can handle **tokens** that only do RSA RAW.  You can tell by what mechs the **modules** supports. And more or less what the **token** supports if the mech lists "hw"

`pkcs11-tool -M` 
Can  you compare ykcs11  vs  opensc-pkcs11?

**Comment by simo5** [comment]
I got this with my yubikey, no support for PSS, and it is using opensc-pkcs11, in any case, there are many different pkcs11 drivers, there is no guarantee a vendor offers RSA_PKCS_PSS from their driver.

**Comment by dengert** [comment]
> I got this with my yubikey, no support for PSS, and it is using opensc-pkcs11.
Hmm. 
I am pretty sure I can do PSS with my Yubikey 5 NFC, with opensc-pkcs11. And since the applet on the card is PIV, PIV only supports RSA RAW.  So any PSS must be done in opensc-pkcs11 or libopensc.   

What command are you using?  I would like to try it.  Maybe some issue with with the OpenSSL -1, -2, -3 extensions to the saltlen.

**Comment by simo5** [comment]
I have a different yubikey that was configured to use the openpgp applet rather than piv, so I reconfigured opensc to use the openpgp driver with this yubikey, and PSS was not supported in that case, and using it results in an pkcs11 error.

I already destroyed the logs, because this is a real token with real PIN etc.. so I do not have more info at this time.

**Comment by dengert** [comment]
Well I ran a test and is same issue as: https://github.com/latchset/pkcs11-provider/issues/187 

So what command are you running?

**Comment by simo5** [comment]
I configure opensc.conf with this:
```
app default {
         debug = 15;
         debug_file = /tmp/opensc-debug.txt;
         card_drivers = openpgp
        framework pkcs15 {
                use_file_caching = no;
                pin_cache_ignore_user_consent = true;
        }
}
```

Then I've run this:
```
$ openssl dgst  -sign "pkcs11:id=%01" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out t.sig t
```

And in spy.log I see this:
```
51: C_GetMechanismInfo
2023-02-14 13:22:33.880
[in] slotID = 0x1
[in] type = CKM_RSA_PKCS_PSS             Returned:  112 CKR_MECHANISM_INVALID

52: C_GetMechanismInfo
2023-02-14 13:22:33.881
[in] slotID = 0x1
[in] type = CKM_SHA384_RSA_PKCS_PSS      Returned:  112 CKR_MECHANISM_INVALID
```

Neither of these mechanism is advertized by opensc when using the openpgp driver with this card apparently, here is the list I fetch at initialization:
```
22: C_GetMechanismList    
2023-02-14 13:22:30.500  
[in] slotID = 0x1
[out] pMechanismList[17]: 
 CKM_SHA_1                     
 Unknown Mechanism (00000255)  
 CKM_SHA256                    
 CKM_SHA384                    
 CKM_SHA512                    
 CKM_MD5                       
 CKM_RIPEMD160                 
 CKM_GOSTR3411                 
 CKM_RSA_PKCS                  
 CKM_SHA1_RSA_PKCS             
 Unknown Mechanism (00000046)  
 CKM_SHA256_RSA_PKCS           
 CKM_SHA384_RSA_PKCS           
 CKM_SHA512_RSA_PKCS           
 CKM_MD5_RSA_PKCS              
 CKM_RIPEMD160_RSA_PKCS        
 CKM_RSA_PKCS_KEY_PAIR_GEN     
Returned:  0 CKR_OK
```

Which clearly shows RSA_PKCS mechanisms but not ESA_PKCS_PSS mechanisms, so, rightfully my code fails to continue as the requested mechanism is not available.

This is why I need to write some sort of fallback for this case.

**Comment by dengert** [comment]
Can you send the whole spy log?

**Comment by simo5** [comment]
As I said this ia a real token I use, so I already re-nuked it after testing.
I do not see why it matters though.
If the pkcs#11 token does not advertise a mechanism I do not even try to use it from pkcs11-provider, so there isn't much to see..

**Comment by dengert** [comment]
Looks like openpgp really only supports CKM_RSA_PKCS. 

if it supported RSA_X_509 then software in libopensc.c can then do any type of padding. 
 
in OpenSC the card drivers (really applet drivers) list what the card/applet can do in hardware. Then OpenSC can then figure out what padding or hashing can be done is software, and present what PKCS11 mechs are supported.  

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/opensc.h#L107-L157

https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-openpgp.c#L512-L514

So OpenPGP supports on card RSA and does padding PKCS1. So what ever data sent to card will be be padded via PKCS1.

**Comment by simo5** [comment]
In this case the only option I have is to just return an error early, instead of going though a bunch of calculations and error late.
