### ISSUE TITLE
EC_GROUP leaks

### ISSUE THREAD

**Issue by manison** [latchset/pkcs11-provider#206]
**Describe the bug**
By skimming the code to parse the EC key object I would say there are missing calls to `EC_GROUP_free` in several places at failure paths:

https://github.com/latchset/pkcs11-provider/blob/f5cae6e82e483b002e6eaa8d4c28891776063571/src/objects.c#L410-L413

https://github.com/latchset/pkcs11-provider/blob/f5cae6e82e483b002e6eaa8d4c28891776063571/src/objects.c#L416-L418

etc.

**Comment by simo5** [comment]
Good catch
