### ISSUE TITLE
Fails basic tests

### ISSUE THREAD

**Issue by mouse07410** [latchset/pkcs11-provider#219]
**Describe the bug**
```
Public Key operation error
8096FA56F87F0000:error:0200007A:rsa routines:p11prov_sig_operate:data too small for key size:signature.c:866:
```
This is as concise as I can see it. ;-)

**To Reproduce**
1. Clone the repo
2. Configure with `OPENSSL_CFLAGS="-I/opt/local/libexec/openssl3/include" OPENSSL_DIR="/opt/local/libexec/openssl3" OPENSSL_LIBS="-L/opt/local/libexec/openssl3/lib -lssl -lcrypto" ./configure --prefix=/opt/local/libexec/openssl3 --disable-silent-rules --with-openssl=/opt/local/libexec/openssl3`
3. `make all && make check`
```
FAIL: basic-softokn
===================

Executing ./tbasic

## Raw Sign check error
openssl pkeyutl -sign -inkey "${BASEURI}" -pkeyopt pad-mode:none -in ${TMPPDIR}/64Brandom.bin -out ${TMPPDIR}/raw-sig.bin
Public Key operation error
8096FA56F87F0000:error:0200007A:rsa routines:p11prov_sig_operate:data too small for key size:signature.c:866:


## Sign and Verify with provided Hash and RSA
openssl dgst -sha256 -binary -out ${TMPPDIR}/sha256.bin ${SEEDFILE}

openssl pkeyutl -sign -inkey "${PRIURI}" -in ${TMPPDIR}/sha256.bin -out ${TMPPDIR}/sha256-sig.bin

openssl pkeyutl -verify -inkey "${PUBURI}" -pubin -in ${TMPPDIR}/sha256.bin -sigfile ${TMPPDIR}/sha256-sig.bin
Signature Verified Successfully

## Sign and Verify with provided Hash and RSA with DigestInfo struct
openssl dgst -sha256 -binary -out ${TMPPDIR}/sha256.bin ${SEEDFILE}

openssl pkeyutl -sign -inkey "${PRIURI}" -pkeyopt digest:sha256 -in ${TMPPDIR}/sha256.bin -out ${TMPPDIR}/sha256-sig.bin

openssl pkeyutl -verify -inkey "${PUBURI}" -pkeyopt digest:sha256 -pubin -in ${TMPPDIR}/sha256.bin -sigfile ${TMPPDIR}/sha256-sig.bin
Signature Verified Successfully
```

Full `tests/test-suite.log` is here: 
[test-suite.log.txt](https://github.com/latchset/pkcs11-provider/files/11044501/test-suite.log.txt)

**Expected behavior**
Passing all the tests.

**Operating environment (please complete the following information):**
 - OS: MacOS Ventura
 - Version 13.2.1
 - Xcode 14.2

**Token and application used (please complete the following information):**
 - Device: SoftHSMv2 2.6.1
 - PKCS11 Driver version: OpenSC master

**Additional context**

**Comment by simo5** [comment]
Uhm we have CI on Mac and it is currently passing with both softokn and softhsm.
That said, the first error is intentional it is checking that we do fail a raw signature if we give an incorrect input.


This is what is failing though:
```
openssl pkey -in $ECBASEURIWITHPIN -pubin -pubout -out ${TMPPDIR}/ec.pub.uripin.pem
Could not open file or uri for loading key from -pubin: No such file or directory
```

I think this may be caused by updating the code without doing a make -C tests clean, which means it would be using old data with new tests.
Do these errors go away if you do: `make -C tests clean && make check` ?
I need to figure out how to know when we should auto-clean the data, without always nuking it, as it is really useful to retain data across tests sometime (also less waiting when you are quickly iterating)

**Comment by mouse07410** [comment]
> Do these errors go away if you do: `make -C tests clean && make check` ?

Thankfully, they did!

> I need to figure out how to know when we should auto-clean the data, without always nuking it, as it is really useful to retain data across tests sometime (also less waiting when you are quickly iterating)

Yes... Offhand, I can only agree here, unfortunately without contributing any useful advice.
