### ISSUE TITLE
Creating self signed certificate using openssl cli requires digest to be explicitly set

### ISSUE THREAD

**Issue by quality-leftovers** [latchset/pkcs11-provider#223]
**Describe the bug**
Tying to generate a self signed certificate using the openssl CLI without digest parameter fails:

```bash
openssl req -x509 -key "$KEY" -outform PEM -subj "/C=DE/CN=test.internal"
```

When explicitly specifying the digest however it woks:

```bash
openssl req -x509 -key "$KEY" -outform PEM -sha256 -subj "/C=DE/CN=test.internal"
# OUTPUT
# -----BEGIN CERTIFICATE-----
# MIIEKzCCApOgAwIBAgIUXwKZcOzkcCySxPL6LOQ5T/zam6kwDQYJKoZIhvcNAQEL
# ...
# -----END CERTIFICATE-----
```

The reason seems to be that `p11prov_mech_by_mechanism` is called with `CK_MECHANISM_TYPE mechanism = 0` because `sigctx->digest` was not set.

**To Reproduce**
Clone commit d58bc51dc96658290e5860be07957764588f7dcc (current master), build and run commands above

**Expected behavior**
Certificate should be generated, just like when pkcs11-provider is not being used. Otherwise documenting this behavior would be nice.

```bash
openssl req -x509 -new -nodes -outform PEM -subj "/C=DE/CN=test.internal"
# Output
# ...
# -----
# -----BEGIN CERTIFICATE-----
# MIIDKzCCAhOgAwIBAgIUY2Y/3FvdJ5woFzxzPGXSRD0qQb4wDQYJKoZIhvcNAQEL
# ...
# WRd67YZhEbHw6GCxlYEtSV0FmozxhP1vN+MdbGpxWb2aIAIyyVUxCpmlKyGLSu8=
# -----END CERTIFICATE-----
```

**Operating environment (please complete the following information):**
 - OS: Ubuntu
 - Version: Lunar / 23.04

**Token and application used (please complete the following information):**
 - Device: SoftHSMv2
 - PKCS11 Driver version: 2.6.1
 - Application: openssl CLI
 - Version: `OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)`

**Additional context**

The openssl CLI docs says something along the lines of

If not specified then SHA1 is used with -fingerprint or the default digest for the signing algorithm is used, typically SHA256.

**Comment by simo5** [comment]
I just tried this and can't reproduce:
```
pkcs11prov (main)]$ openssl req -x509 -key pkcs11://object=ba921591 -outform PEM -subj "/C=DE/CN=test.internal"
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgIUB2spsThfjQO+iuRd+Ghq1HUaq6AwDQYJKoZIhvcNAQEL
BQAwJTELMAkGA1UEBhMCREUxFjAUBgNVBAMMDXRlc3QuaW50ZXJuYWwwHhcNMjMw
NDEyMTQ1NDA0WhcNMjMwNTEyMTQ1NDA0WjAlMQswCQYDVQQGEwJERTEWMBQGA1UE
AwwNdGVzdC5pbnRlcm5hbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AMLtGyRh0l+lXulgcjKaKCwI32bg6oGYnopgizWpCF69Y+pGe0VI9Pu+5Xxv25HT
H6UHbvfpOyMjI6ZexM63YXfkwgRqLLeiimvhRwkz2OaS8PhMHfKdz/AuJ5XNFDF7
F2B6peSQlxGiBJ2ibux2bem4trVO3Rs6WPX/rr9al4YCDTBIBFSRvgXtRM62RslE
c8gboqDPQZy8pGdEd1gq0u00ShmNbKMAI9nOnPhCUxaNAwGPGPxdaqSauaJ/H617
ySfcqYGNyMpHrvO1L6+X2/9x7tkmzcfkZ1GyLGDrxVu6HOaJcPCQKkz4QunXWFS3
S5UZEJjG5XN23DrMghf/y30CAwEAAaNpMGcwHQYDVR0OBBYEFPMUp1mbo2vGrGQx
+HtbagKzmiYiMB8GA1UdIwQYMBaAFPMUp1mbo2vGrGQx+HtbagKzmiYiMA8GA1Ud
EwEB/wQFMAMBAf8wCQYDVR0RBAIwADAJBgNVHRIEAjAAMA0GCSqGSIb3DQEBCwUA
A4IBAQCDpm50Si2nkc6YXAFyazY+Wed8us+9fqzvlFqgY7PaVRvtzm4DGy4HaQEA
IjiTtr78gN/t1PqxVId41T6gEqZlG76cxUsXh0Vf8MqtvBqnA/HQ3Gt2MllVWrvT
WM9r1/UqpZeirJmQu3WO7bXq/4tp2dIkglwvGt1wA8PmhB2422XJL6rHustmfZSQ
LQQqDKAs8F7uYeEZKRBz1e2hrgxQ29BNfg7UPfhGy9m9Ry+zHbawchuwVFhyB8K/
kLTbq8CsEr4e6Ytk5QUZbFwVDYlSkGLCREjVHkRU9uHl2j0vgL3k1cE1HKLKEt7v
9z0350bAUMF3zOqJu0A9f9leX4py
-----END CERTIFICATE-----
```


This is with an RSA key, what did you use to test ?

**Comment by simo5** [comment]
Also could not reproduce with EC Key

**Comment by simo5** [comment]
Ah I know why I could not repdocue I have this in openssl.cnf:
```
[ req ]
default_bits            = 2048
default_md             = sha256
```

If I comment out the default I get:
```
 openssl req -x509 -key $ECPRIURI -outform PEM -subj "/C=DE/CN=test.internal"
00F22CEE3C7F0000:error:40800012:pkcs11:p11prov_GetAttributeValue:Invalid attribute type specified in a template:interface.gen.c:408:Error returned by C_GetAttributeValue
00F22CEE3C7F0000:error:40800012:pkcs11:p11prov_GetAttributeValue:Invalid attribute type specified in a template:interface.gen.c:408:Error returned by C_GetAttributeValue
00F22CEE3C7F0000:error:40800012:pkcs11:p11prov_GetAttributeValue:Invalid attribute type specified in a template:interface.gen.c:408:Error returned by C_GetAttributeValue
00F22CEE3C7F0000:error:40800012:pkcs11:p11prov_GetAttributeValue:Invalid attribute type specified in a template:interface.gen.c:408:Error returned by C_GetAttributeValue
```

Those errors should also not be emitted as they have nothing to do with the issue at hand, but the point is that I do not et a cert either.

This is because we do not have a default digest set when initializing signatures.
I guess we could have one when digest-sign is used...
