### ISSUE TITLE
"Getting started" update 

### ISSUE THREAD

**Issue by baentsch** [latchset/pkcs11-provider#240]
Observations from a first-time user: 

1) Believing [BUILD.md](https://github.com/latchset/pkcs11-provider/blob/main/BUILD.md) I tried building this code base in Ubuntu 22 (which has OpenSSL 3.0+) but failed as it only contains OpenSSL3.0.2... -> Worthwhile updating the docs to state "3.0.7+"? (Yes, sure, I now use my normal local 3.2.0-dev environment using "--with-openssl" :)

2) If libcrypto & libssl are not located in "installpath"/lib but instead "installpath"/lib64, they are not found if there exists (for other libraries) an "installpath"/lib directory --> worthwhile changing the directory test order in https://github.com/latchset/pkcs11-provider/blob/134e4db9af8c60b4e328862a28505653afad14f6/configure.ac#L50-L53 ? Or outright test for availability of the libraries and not just their expected directories?

3) `make` passes then, but `make check` fails in my `--with-openssl" setup as "LIBS" seems to be empty (manually adding "-lcrypto" makes the tests link OK) --> I'm no "autoconf" pro, so any hint as to what I'm missing/doing wrong here very welcome.

**Comment by simo5** [comment]
1. configure has a check for the version of openssl, did it not immediately tell you the available version was not ok
2. And now I understand why 1 is not working, you probably used --with-openssl which do not have this version guard-rail, we can probably reverse the checking order. I think the whole section for --with-openssl can be greatly improved
3. please provide a patch that addresses your concerns if you are so inclined, then we can discuss the merits in the PR

**Comment by baentsch** [comment]
> please provide a patch that addresses your concerns if you are so inclined, then we can discuss the merits in the PR

Would be glad to do so. For 1+2, no problem. 3 I currently still don't understand myself....
