### ISSUE TITLE
Manual page should be generated during the build

### ISSUE THREAD

**Issue by pemensik** [latchset/pkcs11-provider#249]
**Describe the bug**
First line in https://github.com/latchset/pkcs11-provider/blob/main/docs/provider-pkcs11.7#L1 states this is automatically generated file. Which makes sense. I think even if we provide built version in source archive, it should be rebuilt during the build.

It contains `generate-docs` target in root makefile, but that is not called even when pandoc is present. It would make sense to move actual docs building into docs/Makefile.am IMO.

**To Reproduce**
1. Modify `docs/provider-pkcs11.7.md`
2. Have *pandoc* installed
3. run `make`
4. `stat docs/provider-pkcs11.7`
5. Check it was modified.

**Expected behavior**

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version 38

**Additional context**
I think it is *very* confusing to name man page `provider-pkcs11`, when the project is called `pkcs11-provider`. At least alias for the alternative order should be provided.

**Comment by pemensik** [comment]
I think we want also markdown version installed into doc directory.

**Comment by simo5** [comment]
I do not want to force a pandoc dependency, that is why it is not automatically rebuilt.
Distributors are free to rebuild it though.

**Comment by simo5** [comment]
The reason why the manpage is called provider-pkcs11 is that all openssl providers have a provider-something manpage, so I expect normal user will go and try that.

**Comment by simo5** [comment]
> I think we want also markdown version installed into doc directory.

Yes, that we do.

**Comment by pemensik** [comment]
I expected that, but since that is the only manual page shipped, I would expect it to open also when I do `man pkcs11-provider`, the same name as the package.

Of course I don't propose to fail hard if pandoc is not available. But if it is (on Fedora it should be), I think it should recreate the manual page.

**Comment by simo5** [comment]
> > I think we want also markdown version installed into doc directory.
> 
> Yes, that we do.

Looking back, not sure why we would, this is just the source of the manpage, what benefit do we have to install it twice in 2 formats?

**Comment by simo5** [comment]
> I expected that, but since that is the only manual page shipped, I would expect it to open also when I do `man pkcs11-provider`, the same name as the package.
> 
> Of course I don't propose to fail hard if pandoc is not available. But if it is (on Fedora it should be), I think it should recreate the manual page.

What's the gain in recreating it when we have ti already available?

**Comment by pemensik** [comment]
Because we ensure it is always up-to-date, even in case we eventually need it patched downstream.

I would mark the second markdown as %doc, so it can be omitted. Some editors make it nice colored and better looking than just plain man page. I think ideally the rendered man page should be included only to release tarballs, but otherwise removed from git source tree. Though this has low priority.

**Comment by simo5** [comment]
I think we can do this later if there is an actual need, closing now.
