### ISSUE TITLE
a naming conflict with libp11 engine

### ISSUE THREAD

**Issue by avoidik** [latchset/pkcs11-provider#260]
**Describe the bug**

I came to a conclusion that at least on macos produced library name (pkcs11.dylib) has the very same name as in libp11 project (pkcs11.dylib), in my opinion this could be a reason of confusion and potential root cause for configuration issues in future, especially in a condition of openssl engines deprecation

**To Reproduce**

```bash
brew install libp11
```

```bash
git clone https://github.com/latchset/pkcs11-provider.git --branch v0.2 --single-branch
cd pkcs11-provider
autoreconf -fiv
CC=lang ./configure
make -j$(sysctl -n hw.ncpu || echo 2)
sudo make install
ls -la /opt/homebrew/lib/engines-3/
ls -la /usr/local/lib/ossl-modules/
```

```terminal
$ ls -la /usr/local/lib/ossl-modules/pkcs11.dylib
-rwxr-xr-x  1 root  wheel  315289 Jul  8 14:01 /usr/local/lib/ossl-modules/pkcs11.dylib
```

```terminal
$ ls -la /opt/homebrew/Cellar/libp11/*/lib/engines-3/pkcs11.dylib
-r--r--r--  1 username  admin  121232 Jul  6 21:43 /opt/homebrew/Cellar/libp11/0.4.12/lib/engines-3/pkcs11.dylib
```

**Expected behavior**

make changes to produce different filename to avoid potential confusion

**Operating environment (please complete the following information):**
 - OS: macOS
 - Version: 13.4.1 (22F82)

**Token and application used (please complete the following information):**
 - Device: softhsm2
 - PKCS11 Driver version: stable 2.6.1 (bottled), HEAD
 - Application: gpg
 - Version: 2.4.3

**Additional context**

N/A

**Comment by beldmit** [comment]
I'm not sure it's relevant. Providers and engines should be placed in different folders. And I'm afraid, any attempt to load both simultaneously will cause problems.

**Comment by simo5** [comment]
Indeed, this was discussed in the past as well on some issue.
Sorry but engines are the past and providers are the future, and as @beldmit mentioned the modules are installed in different directories so there is no file conflict.
