### ISSUE TITLE
Getting RSA public components no longer working

### ISSUE THREAD

**Issue by fabled** [latchset/pkcs11-provider#265]
Getting RSA public components no longer works. Bisected to commit 00c82644b544f9ac2379dd591577eeeb43a12fb9.

Seems that the removal of public object export in `p11prov_store_export_object` triggered this issue. Adding the removed code back to it makes things work again.

Steps to reproduce:
 1. opened with `OSSL_STORE_open` with pkcs11 URL to match a public RSA key
 2. get `EVP_PKEY` using  `OSSL_STORE_INFO_get1_PUBKEY` for the public key
 3. try to get `e` or `n` with `EVP_PKEY_get_bn_param(pub, OSSL_PKEY_PARAM_RSA_E, &e)`

The above used to work before mentioned commit, but no longer works.

Is this intentional or considered a regression? If intentional, is there any workaround or is it now no longer possible to get the public components of public key?

**Comment by simo5** [comment]
Unexpected side effect, but I need to figure out why I removed it in the end.

**Comment by fabled** [comment]
For reference, I'm now running locally with:
``` diff
diff --git a/src/store.c b/src/store.c
index c76b314..21cfe03 100644
--- a/src/store.c
+++ b/src/store.c
@@ -440,9 +440,28 @@ static int p11prov_store_export_object(void *loaderctx, const void *reference,
                                        size_t reference_sz,
                                        OSSL_CALLBACK *cb_fn, void *cb_arg)
 {
+    P11PROV_OBJ *obj = NULL;
+
     P11PROV_debug("store (%p) export object %p, %zu", loaderctx, reference,
                   reference_sz);
 
+    /* the contents of the reference is the address to our object */
+    obj = p11prov_obj_from_reference(reference, reference_sz);
+    if (!obj) {
+        return RET_OSSL_ERR;
+    }
+
+    /* we can only export public bits, so that's all we do */
+    if (p11prov_obj_get_class(obj) != CKO_PUBLIC_KEY) {
+        return RET_OSSL_ERR;
+    }
+
+    switch (p11prov_obj_get_key_type(obj)) {
+    case CKK_RSA:
+        return p11prov_obj_export_public_rsa_key(obj, cb_fn, cb_arg);
+    case CKK_EC:
+        return p11prov_obj_export_public_ec_key(obj, cb_fn, cb_arg);
+    }
     return RET_OSSL_ERR;
 }
 
```

I can do PR out of this, if it looks like a good idea and there's no other unwanted side effects.

**Comment by simo5** [comment]
So I explored this a bit, and enabling direct export from store functions ends up causing ECDH tests to fail.
I do not understand what is the true cause of this.
However this si not necessary to get the params, I have another change to fix that "properly" which I will open a PR for.

**Comment by fabled** [comment]
I believe the merged commit fixes this. Closing.
