### ISSUE TITLE
Concurrent signing fails intermittently (regression)

### ISSUE THREAD

**Issue by fabled** [latchset/pkcs11-provider#271]
**Describe the bug**
Signing concurrently from multiple threads using same token has intermittent failures.

**To Reproduce**
 1. Get a private key from token
 2. Start N threads
 3. In each thread sign data using key from step 1
 4. Depending on timing of things, a signing operation can fail intermittently with:
```
dnssec-signzone: info: error:4080000A:pkcs11::Internal locking failure:session.c:621:Failed to fetch a login_session
dnssec-signzone: info: error:4080000A:pkcs11::Internal locking failure:signature.c:837:Failed to open session on slot 131283951
```

**Expected behavior**
No errors during signing.

**Additional context**
It seems that since commit https://github.com/latchset/pkcs11-provider/commit/6403f22383f8c00860eb422a75c17a6968fb3a13 fetch_session will immediately fail if two threads are concurrently doing the first operation on a slot that would need login.

It seems that setting `reqlogin` in https://github.com/latchset/pkcs11-provider/blob/main/src/signature.c#L807 triggers `p11prov_get_session` to call `slot_login` which has this race.

Additionally this will cause all threads to serialize to have access for the login session even if already logged in. Since all session share login state, it might make sense to first get a session from the pool, and check the logged in state from it. Only if not-logged in, fall back to the slow path of acquiring the login session.

**Comment by simo5** [comment]
Sounds like this goes hand in hand with #270

**Comment by fabled** [comment]
> Sounds like this goes hand in hand with #270

In my case, pkcs11-provider still needs to do login on first use. This is more about how concurrent actions are synchronized. But I suppose there is some overlap with these two tickets.

**Comment by simo5** [comment]
I f we have a check for session login existing I think we could relax the serialization on login session ... need to think about it

**Comment by simo5** [comment]
@fabled, is there something left here todo or does #273 cover this fully?
