### ISSUE TITLE
Test coverage for key comparison and getting public key data from EdDSA

### ISSUE THREAD

**Issue by Jakuje** [latchset/pkcs11-provider#272]
The PR #267 added key comparison test `tcmpkeys` which runs for RSA and EC keys, but there is no test coverage for EdDSA keys. The implementation should be complete though.

It also added reading of public attributes from the generated keys in `tgenkey`, but also without EdDSA coverage, which needs to be added somehow separately (as the EdDSA is available only in SoftHSM for now).

BTW when is the NSS getting EdDSA support? There were some patches, werent they?

**Comment by simo5** [comment]
I am trying to extend the simple pub key loading tests, but I get a failure to load the public key from the produce pem file.

A quick gdb of the test shows OSSL_STORE_INFO_get_type() returning an entry of type OSSL_STORE_INFO_PARAMS which confuses me.

**Comment by simo5** [comment]
Apparently have to explicitly tell the store to expect a public key, otherwise it attempts to load a private key and gets only params ... somehow...

**Comment by Jakuje** [comment]
> Apparently have to explicitly tell the store to expect a public key, otherwise it attempts to load a private key and gets only params ... somehow...

This works as a workaround for the key comparison, but usually one wants also the private key.

Anyway most of this (except the proposed workaround) is already described in #292, in openssl/openssl#22246 and likely fixed in ossl 3.2 (openssl/openssl/pull#21219).
