### ISSUE TITLE
Error from OSSL_STORE_load is masked by EOF indication

### ISSUE THREAD

**Issue by manison** [latchset/pkcs11-provider#274]
**Describe the bug**
When `OSSL_STORE_load` fails because of an error the following `OSSL_STORE_error` returns `false` while `OSSL_STORE_eof` returns `true`.

**To Reproduce**
1. Open the store and make `OSSL_STORE_load` fail (e.g. bad URI so the store cannot open the session)
2. Check return value from `OSSL_STORE_error`

**Expected behavior**
When `OSSL_STORE_load` fails because of an error the following `OSSL_STORE_error` returns `true`.

**Operating environment (please complete the following information):**
 - OS: Debian
 - Version: sid

**Token and application used (please complete the following information):**
 - Device: SoftHSM2

**Additional context**
* OpenSSL 3.1.1

This is because OpenSSL's `OSSL_STORE_load` sets an internal error flag only when the store provider does not report EOF, see https://github.com/openssl/openssl/blob/7c729851d169f30d9e0c0ad6e7c1cf6cefb37935/crypto/store/store_lib.c#L432-L438

**Comment by manison** [comment]
Additional info: This was tested on 37461931, thus before #273. The URI must be valid and good, otherwise `OSSL_STORE_open` will fail first. The inner `store_fetch` fails (in this particular case because of #270 - it could not retrieve proper session) and sets `ctx->loaded` to `-1`. This error condition is then interpreted by `p11prov_store_eof` as an EOF condition which leads to the above mentioned consequences.

**Comment by simo5** [comment]
@manison when you write:
"When OSSL_STORE_load fails because of an error the following OSSL_STORE_error returns true."
Do you actually mean OSSL_STORE_eof returns true ?

**Comment by simo5** [comment]
Ok, so I suspect what you are asking here is that in case of error we should *not* return true from _eof() ?

**Comment by simo5** [comment]
Looks like this will be fixed upstream by https://github.com/openssl/openssl/pull/21976
Therefore closing this issue, you can follow the upstream one to see when a fix will become available.
