### ISSUE TITLE
Create keys in a specific token/slot

### ISSUE THREAD

**Issue by matje** [latchset/pkcs11-provider#279]
**Describe the feature**

When generating keys, it would be nice to set the specific token/slot where the key needs to be generated.

**Expected behavior**

When generating the key with for example EVP_PKEY_generate(), the key is created in the specified token. The token I expect can be set with in the OSSL_PARAM array, similar to the object/label: 
```
        params[0] = OSSL_PARAM_construct_utf8_string("pkcs11_key_label", label, 0);
```

Alternatively, one param entry could take an RFC 7512 PKCS#11 string that may contain the `object` and `token`.

**Additional context**

For context, I am working on making DNSSEC policy in BIND 9 work with HSMs using the OpenSSL PKCS#11 Provider.

**Comment by simo5** [comment]
Yes, this is a known open issue.

I am considering have a URI param instead individual custom parameters, where you can specify any of the IETF standard URI parameters including the token identifier you want to use.

Would that work in this case?

**Comment by matje** [comment]
Do you mean for example 
```
        uri = "pkcs11:token=token-name;pin-value=1234";
        params[0] = OSSL_PARAM_construct_utf8_string("pkcs11_uri", uri, 0);
```

If something like that, this would be ideal for me personally, it would be the same as the URI you put into the BIND 9 configuration.

**Comment by simo5** [comment]
> Do you mean for example
> 
> ```
>         uri = "pkcs11:token=token-name;pin-value=1234";
>         params[0] = OSSL_PARAM_construct_utf8_string("pkcs11_uri", uri, 0);
> ```

Yes, and the fact you put the pin there is also one of the bonuses, it means you can authenticate write access to the token even if you did not have the pin stored already.

> If something like that, this would be ideal for me personally, it would be the same as the URI you put into the BIND 9 configuration.

Exactly, that URI, if properly formatted, would be the same used to retrieve the key later.

**Comment by fabled** [comment]
I think we could just allow full URI specification here. If `label` or `id` is specified, it could be stuffed into the template to instantiate the object with the given URI spec.

**Comment by fabled** [comment]
Application should be able to specify also the key usage. Especially in RSA keys having a key that can sign and decrypt is considered bad practice. Should this be made separate issue?

**Comment by socketpair** [comment]
@matje  how to generate keys using openssl through pkcs11 library?

**Comment by matje** [comment]
> [@matje](https://github.com/matje) how to generate keys using openssl through pkcs11 library?

The `openssl` command is not my use case, so I probably don't have the best answer, but assuming you use providers (not engines), I guess you have to set the right `-provider` name, `-provider-path` path, and `-propquery` property. Also make sure your `openssl.cnf` includes the right provider configuration.

**Comment by socketpair** [comment]
@matje Yes, Signing works through provider (not engine).  But the question is still actual - what command line (or API) should I use to generate keys on my USB stick through OpenSSL ?

**Comment by matje** [comment]
`genpkey`? Honestly, it depends on your environment, and an engine search is better more suitable.
