### ISSUE TITLE
Key generation should allow specifying key usage

### ISSUE THREAD

**Issue by fabled** [latchset/pkcs11-provider#285]
When generating a new key, the application should be able to specify key usage in the context parameters (sign/verify, encrypt/decrypt). Current all keys are generated with all usage allowed.

But it is not recommended to generate RSA private keys that can be used both for signing and decryption.

**Comment by fabled** [comment]
As mentioned in the first message, I'd add some pkcs11-provider specific context parameters that control this. Similar to `pkcs11-uri`. Just add `pkcs11-usage-sign-verify` and `pkcs11-usage-decrypt-encrypt`. Sign and verify go together (for private and public key respectively).

**Comment by simo5** [comment]
Uhmm, this would require the application to know exactly what provider is used, but I guess it is better than nothing.
I do not think we want to add many parameters, probably just one that is a string (or even a bitfield) like `pkcs11_key_usage = sign,verify,encrypt,decrypt`, we need to list all usages we need to support and what the defaults should be.

**Comment by fabled** [comment]
> Uhmm, this would require the application to know exactly what provider is used, but I guess it is better than nothing.
> I do not think we want to add many parameters, probably just one that is a string (or even a bitfield) like `pkcs11_key_usage = sign,verify,encrypt,decrypt`, we need to list all usages we need to support and what the defaults should be.

It already needs to do so if it wants to name the object or place it in specific object. So `pkcs11_uri` needs to be set. Normally the provider needs to be explicitly requested via `provider=pcks11` argument to `EVP_PKEY_CTX_new_from_name`.

But agreed, better to keep these to minimum.

Normal openssl objects enforce the usage only for certificates, and raw keys do not have this kind of usage policy. The fact that pkcs#11 implements the usage on raw object level brings the need of this extra mapping.

Will next review the PR.
