### ISSUE TITLE
Unable to compile on Ubuntu 14.04.6 LTS needed for ARM cross-compile

### ISSUE THREAD

**Issue by blackbird1** [latchset/pkcs11-provider#290]
**Describe the bug**
I'm using a lower version of Ubuntu in order to cross-compile for different ARM architectures

**To Reproduce**
1. echo $(pkg-config --version)
0.26
2. CFLAGS="-march=armv7-a" ./configure --with-openssl=$BUILD_INSTALL_PREFIX --prefix=$BUILD_INSTALL_PREFIX --host=$BUILD_CROSS_COMPILE_HOST

Output:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-gnueabihf-strip... arm-linux-gnueabihf-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-linux-gnueabihf-gcc... arm-linux-gnueabihf-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-linux-gnueabihf-gcc accepts -g... yes
checking for arm-linux-gnueabihf-gcc option to accept ISO C89... none needed
checking whether arm-linux-gnueabihf-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of arm-linux-gnueabihf-gcc... gcc3
checking for arm-linux-gnueabihf-ar... arm-linux-gnueabihf-ar
checking the archiver (arm-linux-gnueabihf-ar) interface... ar
checking build system type... aarch64-unknown-linux-gnu
checking host system type... arm-unknown-linux-gnueabihf
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by arm-linux-gnueabihf-gcc... /usr/arm-linux-gnueabihf/bin/ld
checking if the linker (/usr/arm-linux-gnueabihf/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/arm-linux-gnueabihf-nm -B
checking the name lister (/usr/bin/arm-linux-gnueabihf-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert aarch64-unknown-linux-gnu file names to arm-unknown-linux-gnueabihf format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/arm-linux-gnueabihf/bin/ld option to reload object files... -r
checking for arm-linux-gnueabihf-objdump... arm-linux-gnueabihf-objdump
checking how to recognize dependent libraries... pass_all
checking for arm-linux-gnueabihf-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-linux-gnueabihf-ar... (cached) arm-linux-gnueabihf-ar
checking for archiver @FILE support... @
checking for arm-linux-gnueabihf-strip... (cached) arm-linux-gnueabihf-strip
checking for arm-linux-gnueabihf-ranlib... arm-linux-gnueabihf-ranlib
checking command to parse /usr/bin/arm-linux-gnueabihf-nm -B output from arm-linux-gnueabihf-gcc object... ok
checking for sysroot... no
checking for arm-linux-gnueabihf-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking how to run the C preprocessor... arm-linux-gnueabihf-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if arm-linux-gnueabihf-gcc supports -fno-rtti -fno-exceptions... no
checking for arm-linux-gnueabihf-gcc option to produce PIC... -fPIC -DPIC
checking if arm-linux-gnueabihf-gcc PIC flag -fPIC -DPIC works... yes
checking if arm-linux-gnueabihf-gcc static flag -static works... yes
checking if arm-linux-gnueabihf-gcc supports -c -o file.o... yes
checking if arm-linux-gnueabihf-gcc supports -c -o file.o... (cached) yes
checking whether the arm-linux-gnueabihf-gcc linker (/usr/arm-linux-gnueabihf/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for arm-linux-gnueabihf-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether C compiler accepts -std=c11... yes
./configure: line 11875: syntax error near unexpected token `STD_CFLAGS="-Wall -Wextra -Wwrite-strings -Wpointer-arith -Wno-missing-field-initializers -Wformat -Wshadow"'
./configure: line 11875: `STD_CFLAGS="-Wall -Wextra -Wwrite-strings -Wpointer-arith -Wno-missing-field-initializers -Wformat -Wshadow"'

**Expected behavior**
Compile provider source for each ARM target.

**Operating environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 14.04.6 LTS

**Token and application used (please complete the following information):**
 - Device: Ubuntu Docker 
 - PKCS11 Driver version: N/A
 - Application N/A
 - Version 0.2

**Comment by simo5** [comment]
I do not think Ubuntu 14 has an OpenSSL version new enough to compile, in any case I do not know how cross compiling work in this case and why it breaks.

I will leave this open a few days in cases someone sees this and has an idea, but I can't help you.

**Comment by blackbird1** [comment]
I'm cross-compiling my dependencies manually in order to support the different ARM variations I need. Supporting cross-compile for "arm-linux-gnueabihf" and "arm-linux-gnueabi" would be nice. Below is how OpenSSL supports it. 

OpenSSL 3:
./Configure linux-generic32 fips shared --openssldir=$INSTALL_DIR --prefix=$BUILD_INSTALL_PREFIX --cross-compile-prefix=arm-linux-gnueabihf- -march=armv7-a -latomic '-Wl,-rpath,/usr/local/vmware/lib' && \
    make && make install

**Comment by Jakuje** [comment]
The line with `STD_CFLAGS` comes after the `AX_VALGRIND_CHECK()`, which might have some compatibility issues with some of the tools you have in the old ubuntu -- please investigate or provide `config.log` to see what it does not like about that and if there are some versions to check. 

Other guess might be using `--disable-valgrind`, but given that the `ax_valgrind_check.m4` is not bundled but provided by the autoconf-archive, it might be very old and very different version. One option might be to bundle this into the `m4` directory. You can get the current version from

http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_valgrind_check.m4
