### ISSUE TITLE
Test that importing private keys from PEM files (or even just memory buffers) into session objects works

### ISSUE THREAD

**Issue by simo5** [latchset/pkcs11-provider#305]
We want to be able to work in an openssl configuration where the only provider configured is the pkcs11-provider, in that case we need to be able to import both public and private keys into sessions objects for tokens that can handle all operations (eg soft tokens).

This is because people may end up using a mix of in-token and out of token keys in applications where the main usage dictates use of in-token only keys, but some auxiliary libraries try to use keys from files, or from memory for some functions (like checking signatures, decrypting data, and what not).

**Comment by beldmit** [comment]
It will not work with _the only_ pkcs11 provider configured - or we have to import/implement decoder stuff into it. We still need base or default provider

**Comment by simo5** [comment]
I think needing the base provider is fine.
