### ISSUE TITLE
openssl pkey command with softhsm2 fails

### ISSUE THREAD

**Issue by gilweis** [latchset/pkcs11-provider#310]
**Describe the bug**
Segmentation fault (core dumped)

**To Reproduce**
$ openssl pkey -in "pkcs11:type=public;id=%02" -pubin -pubout -out testkey2.pub

**Operating environment (please complete the following information):**
 - OS: Ubuntu 23.10
 - openssl: OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
 - pkcs11-provider: latest / 0.2
 - softhsm2: 2.6.1

**Additional context**
$ openssl pkey -in "pkcs11:type=public;id=%02" -pubin -pubout -out testkey2.pub
Segmentation fault (core dumped)

$ strace openssl pkey -in "pkcs11:type=public;id=%02" -pubin -pubout -out testkey2.pub
...
openat(AT_FDCWD, "/home/g/tokens//a35f1b46-7963-fae0-dcb4-ae2b21f802c7/013c5fb0-8ba9-ed7b-a52e-3ae79f01d0e1.object", O_RDONLY) = 4
fcntl(4, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fcntl(4, F_SETLKW, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
newfstatat(4, "", {st_mode=S_IFREG|0600, st_size=680, ...}, AT_EMPTY_PATH) = 0
read(4, "\0\0\0\0\0\0\0\35\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\2"..., 4096) = 680
fcntl(4, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
close(4)                                = 0
newfstatat(3, "", {st_mode=S_IFREG|0664, st_size=0, ...}, AT_EMPTY_PATH) = 0
write(3, "-----BEGIN RSA PUBLIC KEY-----\nM"..., 251) = 251
close(3)                                = 0
getpid()                                = 4108
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by simo5** [comment]
This is a known issue in softhsm which is basically broken.
See for example https://github.com/openssl/openssl/issues/22508
You can use a workaround to try to get things somewhat working by setting `pkcs11-module-quirks = no-deinit`, see https://github.com/latchset/pkcs11-provider/blob/main/docs/provider-pkcs11.7.md#pkcs11-module-quirks
