### ISSUE TITLE
Implement session pooling or caching

### ISSUE THREAD

**Issue by fabled** [latchset/pkcs11-provider#32]
Current strategy is to create PKCS11 sessions on the spot when needed. However is not ideal from interoperability and performance:
 - Some modules may have hard limit on few or even one concurrent session. In this case the first thread gets the sessions, and other threads will fail with failure to create session.
 - Other modules may support indefinite sessions, but have large CPU/time overhead on creation the session (e.g. session maps directly to a TCP connection). Thus using cache or pool of sessions could remove this overhead.
 - Also, as further optimization, if logging in to session is needed to use the key/object, we can remove need for extra logins for consecutive use of object if session is kept in logged-in state.

Additional potential PKCS11 complication to account for is that all sessions share the logged-in user and state. Thus some operations might be possible if there are sessions using from logged-in user (e.g. some thread doing crypto as normal user, but another thread wanting to create/delete objects needing SO user).

This ticket is to discuss the strategy to manage sessions and concurrent access.

Two options to consider:
 - Implement session pooling similar to [libp11's pooling](https://github.com/OpenSC/libp11/commit/4bd92da60a670e3c25d9cb69fca3363f47a225c7). Down side is the need for locking even in single threaded use cases.
 - Using per-thread cached session in pthread "setspecific" area. These can have a destructor associated so sessions can be cleaned up on thread exit. Additionally C_CloseAllSessions can be used to flush them globally if needed.

Perhaps additional options brew up during discussion of the problem.

**Comment by simo5** [comment]
Do we have to deal with the case where a SO session is needed in the openssl provider at all ?
I kind of assume the openssl provider always operates in user mode and leaves to specialized tools provided by the token manufacturer to deal with super user sessions.

By avoiding dealing with SO session we can greatly simplify some cases (namely need to SO login (and how to tell that to the provider) when a user login session is open.

**Comment by simo5** [comment]
Ok, I would like to document we do not support SO operations in the current design and leave it out completely.
As you said it is highly token specific, and openssl really does not have much in the way of support for privileged operations.

It does support key creation but I do not know that it is a good idea to use openssl pkey to generate something on a token anyway. Key generation should be used generally just for ephemeral key operations, and we'll need to decide what to do with tokens that are so crummy they didn't bother to support session objects (as opposed to token objects) which are ephemeral and do not require write permissions to the token.
