### ISSUE TITLE
Extend operation state quirk to cover all operation state operations.

### ISSUE THREAD

**Issue by simo5** [latchset/pkcs11-provider#327]
PR #324 introduced the ability to set a configuration quirk so that trying to save the state is not even attempted.

This should be extended to all uses of the operation state function.
Ideally by checking for the quirk within the body of the operation state wrapper itself.

**Comment by simo5** [comment]
@sahanaprasad07 can you pick this one up in the future?

**Comment by sahanaprasad07** [comment]
Hi @simo5 , which other operation state do you mean here? GetOperationState is only called in signature.c and digests.c. Operate state quirk seems to be covered in both these places already.

**Comment by simo5** [comment]
I think the switch should be checked within the GetOperationState interface function, instead of checking for it in all the places where it is called.

So it is a matter of special casing this function like I did here: https://github.com/latchset/pkcs11-provider/blob/e2abc4a7ae33159f2fb21b9d87a05ea9e79ef584/src/interface.c#L455 for the Decrypt interface.

The only difference is that we completely replace the auto-generated "Get/SetOperationState" functions from interface.pre instead of just adding a special case.

**Comment by simo5** [comment]
Or maybe we find a generic way to block any function call and add the same code to all, it could be done with a bitfield store on the provider context and then have a generic check in the autogenerated functions.
Most functions would never be blocked but this would allow us to selectively block calls which could be used in testing as well.
