### ISSUE TITLE
SSL with pkcs11-provider private key: sequence of SSL_CTX_new and OSSL_STORE_open_ex matters

### ISSUE THREAD

**Issue by space88man** [latchset/pkcs11-provider#352]
**Describe the bug**
https://github.com/openssl/openssl/tree/openssl-3.2.1/demos/sslecho

Create a modified  sslecho server using a pkcs11-provider private key(NSS softoken).

s_client fails depending on the sequence of OSSL_STORE_open_ex and  SSL_CTX_new

**To Reproduce**

Two examples using softtoken

* fail: SSL_CTX_new before OSSL_STORE_open_ex
[example-fail.zip](https://github.com/latchset/pkcs11-provider/files/14461489/example-fail.zip)
* pass: SSL_CTX_new after OSSL_STORE_open_ex
[example-pass.zip](https://github.com/latchset/pkcs11-provider/files/14461490/example-pass.zip)
* soft token
[softtoken.zip](https://github.com/latchset/pkcs11-provider/files/14461491/softtoken.zip)

```
KEY_URI="pkcs11:id=%7a%8f%17%4b%4f%a0%7c%88%fa%a8%a3%d8%f6%83%19%b8%94%4d%15%55"
CERT_PEM=testCert.pem
./sslecho s

# with the fail example  SSL_CTX_new before OSSL_STORE_open_ex

openssl s_client -connect localhost:4433

$ KEY_URI="$KEY_URI"  CERT_PEM=testCert.pem  ./sslecho s

sslecho : Simple Echo Client/Server (OpenSSL 3.0.1-dev) : Mar  1 2024 : 21:04:08

found private key = 0x1dadea0
We are the server on port: 4433

Client TCP connection accepted
404C5D66BC7F0000:error:0A000076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl/t1_lib.c:3280:
Server exiting...
sslecho exiting

```
**Expected behavior**
With the pass example

```
$ KEY_URI="pkcs11:id=%7a%8f%17%4b%4f%a0%7c%88%fa%a8%a3%d8%f6%83%19%b8%94%4d%15%55" 
CERT_PEM=testCert.pem  ./sslecho s

sslecho : Simple Echo Client/Server (OpenSSL 3.0.1-dev) : Mar  1 2024 : 21:03:17

found private key = 0xec6880
We are the server on port: 4433

Client TCP connection accepted
Client SSL connection accepted
```

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version :39

**Token and application used (please complete the following information):**
 - NSS softtoken 3.96

**Additional context**
- [update] can reproduce with EC key from softoken - so it is not related to key type

**Comment by simo5** [comment]
The key uri is underspecified, please add type=private; in the uri, and it will work correctly.

For public/private key pair the type is basically always required exactly because by convention both parts of the key (which is stored as two separate object in pkcs#11) have the same object id (so they can be easily correlated).

**Comment by simo5** [comment]
Hint: to get a "known good" URI use the openssl storeutl command to list all keys in the token.
For each key you will see an extra uri argument that tells you what is the uri to use to uniquely identify the key.

**Comment by space88man** [comment]
> The key uri is underspecified, please add type=private; in the uri, and it will work correctly.
> 
Question: even if the key is underspecified shouldn't the expect on the store reduce the ambiguity?

The issue is reproducible even with the full URI
```
KEY_URI="pkcs11:model=NSS%203;manufacturer=Mozilla%20Foundation;serial=0000000000000000;token=NSS%20Certificate%20DB;id=%7A%8F%17%4B%4F%A0%7C%88%FA%A8%A3%D8%F6%83%19%B8%94%4D%15%55;type=private" CERT_PEM="testCert.pem" ./sslecho s


sslecho : Simple Echo Client/Server (OpenSSL 3.0.1-dev) : Mar  1 2024 : 21:04:08

found private key = 0x683160
We are the server on port: 4433

Client TCP connection accepted
402CDAD4557F0000:error:0A000076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:ssl/t1_lib.c:3280:
Server exiting...
sslecho exiting

$ openssl s_client -connect 127.0.0.1:4433 -CAfile selfCA.pem 
```

**Comment by simo5** [comment]
At the moment we do not use the expect parameters to further filter the findings from the store.
I guess we could indeed. I would accept a reasonable patch to do that.

**Comment by space88man** [comment]
> At the moment we do not use the expect parameters to further filter the findings from the store. I guess we could indeed. I would accept a reasonable patch to do that.

In any case - I don't think the URI is the issue here: both s_server and sslecho check for `OSSL_STORE_INFO_PKEY` and manage to find the correct private key (whether  full or short form) - so pkcs11-provider is free to return other objects like public keys/certs and they will be filtered out.

What is surprising is the order of OSSL_STORE_open_ex and SSL_CTX_new.

**Comment by space88man** [comment]
- so long as the provider is loaded by OSSL_STORE_open_ex first , before SSL_CTX_new then it works. It doesn't even have to be a correct URI

```
// this will allow SSL to work
OSSL_STORE_open_ex("pkcs11:token=dummy;object=dummy;type=cert") ....
SSL_CTX_new(...)
```

**Comment by simo5** [comment]
Does the difference go away if you set `pkcs11-module-load-behavior = early` in the provider configuration?

**Comment by simo5** [comment]
Well it is not a solution, it is just a workaround that have many other undesirable side-effects.

We are working on finding what is causing this discrepancy so we can avoid setting that option. If you do use it I strongly suggest you use a separate openssl conf file for the time being, used only by the application that needs it, otherwise you may have issue in other regular applications, especially if using softhsm2 as a soft token.

@The-Mule I think this is the same thing you are seeing in testing HTTPD.

**Comment by space88man** [comment]
> Well it is not a solution, it is just a workaround that have many other undesirable side-effects.
> 
> We are working on finding what is causing this discrepancy so we can avoid setting that option. If you do use it I strongly suggest you use a separate openssl conf file for the time being, used only by the application that needs it, otherwise you may have issue in other regular applications, especially if using softhsm2 as a soft token.
> 
> @The-Mule I think this is the same thing you are seeing in testing HTTPD.

One more data point, if I do `SSL_CTX_new` in the default context, and then explicitly create a new context and set that as default, then SSL would work

```
ctx = SSL_CTX_new()

// now switch context
new_libctx = OSSL_LIB_CTX_new();
orig_libctx = OSSL_LIB_CTX_set0_default(new_libctx);
CONF_modules_load_file(CONF_get1_default_config_file(), NULL, 0L);

// ... use OSSL_STORE_open to find find private key etc
```

**Comment by simo5** [comment]
@space88man any chance you can test if #372 addresses any or all the issues you raised here?

**Comment by simo5** [comment]
(please test *without* the `pkcs11-module-load-behavior = early` quirk)

**Comment by space88man** [comment]
Yes: https://github.com/latchset/pkcs11-provider/pull/372 fixes this issue.

With this commit the order of SSL_CTX_new and OSSL_STORE_open doesn't matter.
For the record: openssl s_server just happened to load the private key first, that's why it always worked.
OTOH sslecho call SSL_CTX_new before loading the private key.

**Comment by simo5** [comment]
Great, thanks for confirming.
