### ISSUE TITLE
PEM PKCS#11 key URI doesn't work if it is not the first object

### ISSUE THREAD

**Issue by space88man** [latchset/pkcs11-provider#364]
**Describe the bug**
When the private key is loaded from a PEM file with `BEGIN PKCS#11 PROVIDER URI`
it doesn't work if it is not the first object when using `PEM_read_bio_PrivateKey`. 

Discovered this when using the PEM feature in HAProxy which loads private keys using
`PEM_read_bio_PrivateKey` instead of `OSSL_store_open`.

No errors in debug at level 9, no errors using `ERR_print_errors_fp`.

OTOH using  `OSSL_STORE_open` works.

**To Reproduce**
1. Create PEM with `BEGIN PKCS#11 PROVIDER URI`
2. Add another PEM object above the file e.g.`-----BEGIN CERTIFICATE-----`

**Expected behavior**
Can load private key with `PEM_read_bio_PrivateKey` from a PEM file.

**Operating environment (please complete the following information):**
 - Fedora 
 - 39

**Token and application used (please complete the following information):**
 - Device: NSS Softoken
 - PKCS11 Driver version: 3.96
 - test program

**Additional context**
[provider-pem.zip](https://github.com/latchset/pkcs11-provider/files/14681326/provider-pem.zip)

* `pub2-key.pem` is a key-only file
* `pub2.pem` has a cert above the private key

**Comment by simo5** [comment]
I do not think there was ever the intention of supporting mixed files, but I asusme in some cases people want to bundle certs with private key references ...
@0pq76r do you know if we can do something about this ?

**Comment by 0pq76r** [comment]
I tried it with 2 different tokens and ossl versions and was not able to reproduce the described problem.
(openssl 3.0.8 with token Securosys Primus HSM, openssl 3.3.0-dev-g4514e02cdfc9 with token nss-3.88.1 libsoftokn3.so)

When a private key with the label "testCert-private" exists on the token, your demo application returned a non-null pkey in for both pub2.pem and pub2-key.pem.

Are you sure the key you are looking for ("pkcs11:object=testCert-private;type=private") is in the token and unique?
(Your openssl-pem.cnf uses "configDir=tokens2" but you shared the "tokens" directory in the zip.)
Is the pin in your pinfile correct?
Which OSSL version are you using?

**Comment by space88man** [comment]
Closing as I cannot reproduce the issue now. Sorry for the noise.
