### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by bith3ad** [latchset/pkcs11-provider#394]
Please release a new version. The current v0.3 does not built out-of-the-box with Yocto (https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-support/pkcs11-provider/pkcs11-provider_0.3.bb?h=master) due to `fallthrough` issues which are already fixed in main.

A proper release which builtsystems can use instead of the current main branch.

**Comment by simo5** [comment]
Done: https://github.com/latchset/pkcs11-provider/releases/tag/v0.4
