### ISSUE TITLE
RSA PSS CKA_ALLOWED_MECHANISMS attributes size

### ISSUE THREAD

**Issue by omasse-linaro** [latchset/pkcs11-provider#396]
According to the spec https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/os/pkcs11-spec-v3.1-os.html#_Toc111203229
CKA_ALLOWED_MECHANISMS attribute is a list of mechanisms with number of elements is the ulValueLen component of the attribute divided by sizeof(CK_MECHANISM_TYPE)

However, in the keymgmt.c code at the following line:
https://github.com/latchset/pkcs11-provider/blob/d8e2823bee2268782ec70036618622ee7e87749e/src/keymgmt.c#L1006

ulValueLen is set to the number of elements and not the size of the array in bytes. Which seems to not follow the spec definition of a CK_ATTRIBUTE as well:
The fields of the structure have the following meanings:
                                           type       the attribute type
                                       pValue       pointer to the value of the attribute
                                 ulValueLen       **length in bytes of the value**

Is there some reasons why it is not aligned with the 3.1 specification ?

**Comment by simo5** [comment]
Sounds like it is just a bug ... do you have a token that supports this attribute we can test against?

**Comment by omasse-linaro** [comment]
yes, and we can provide a patch.

**Comment by simo5** [comment]
@omasse-linaro please check #397 it should fix the problem
