### ISSUE TITLE
Meson build system jank in nixpkgs

### ISSUE THREAD

**Issue by numinit** [latchset/pkcs11-provider#409]
**Describe the bug**
Hi there! I maintain pkcs11-provider in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/pk/pkcs11-provider/package.nix#L9) and am running into some build system jank with Meson.

**To Reproduce**
Build with Meson against an OpenSSL on a readonly filesystem. You get a PermissionError because the installer tries to mutate an immutable path. Setting DESTDIR in mesonInstallFlags causes more problems since the two paths don't share a prefix; see below.

**DESTDIR not set: fails to install in OpenSSL root since it's readonly**

```
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
mesonInstallPhase flags: ''
Installing src/pkcs11.so to /nix/store/8bdd933v69w05k5v8hfcq74bi1f9545k-openssl-3.0.13/lib/ossl-modules
Traceback (most recent call last):
  File "/nix/store/rxxlbwh0qxkwb2n0infcprw0ijkxn2x7-meson-1.4.0/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 186, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rxxlbwh0qxkwb2n0infcprw0ijkxn2x7-meson-1.4.0/lib/python3.11/site-packages/mesonbuild/minstall.py", line 863, in run
    installer.do_install(datafilename)
  File "/nix/store/rxxlbwh0qxkwb2n0infcprw0ijkxn2x7-meson-1.4.0/lib/python3.11/site-packages/mesonbuild/minstall.py", line 543, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/nix/store/rxxlbwh0qxkwb2n0infcprw0ijkxn2x7-meson-1.4.0/lib/python3.11/site-packages/mesonbuild/minstall.py", line 740, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(dm, outdir))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/rxxlbwh0qxkwb2n0infcprw0ijkxn2x7-meson-1.4.0/lib/python3.11/site-packages/mesonbuild/minstall.py", line 420, in do_copyfile
    self.copy2(from_file, to_file)
  File "/nix/store/rxxlbwh0qxkwb2n0infcprw0ijkxn2x7-meson-1.4.0/lib/python3.11/site-packages/mesonbuild/minstall.py", line 317, in copy2
    shutil.copy2(*args, **kwargs)
  File "/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python3.11/shutil.py", line 448, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/nix/store/8bdd933v69w05k5v8hfcq74bi1f9545k-openssl-3.0.13/lib/ossl-modules/pkcs11.so'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
```

**DESTDIR set to $out: install directory is wrong**

```
Running phase: installPhase
mesonInstallPhase flags: ''
Installing src/pkcs11.so to /nix/store/0j4cbfzi9r0nb34l2ah8vr46afij81gz-pkcs11-provider-0.5/nix/store/8bdd933v69w05k5v8hfcq74bi1f9545k-openssl-3.0.13/lib/ossl-modules
Installing /build/source/docs/provider-pkcs11.7 to /nix/store/0j4cbfzi9r0nb34l2ah8vr46afij81gz-pkcs11-provider-0.5/nix/store/0j4cbfzi9r0nb34l2ah8vr46afij81gz-pkcs11-provider-0.5/share/man/man7
```

**Expected behavior**
The files are installed into the intended directory, not the OpenSSL one. The following workaround is necessary to prevent this from occurring:

```
preInstall = ''
    # Meson tries to install to `$out/$out` and `$out/''${openssl.out}`; so join them.
    mkdir -p "$out"
    for dir in "$out" "${openssl.out}"; do
      mkdir -p .install/"$(dirname -- "$dir")"
      ln -s "$out" ".install/$dir"
    done
    export DESTDIR="$(realpath .install)"
'';
```

Is there an easier way to do this?

**Operating environment (please complete the following information):**
 - OS: nixpkgs

**Comment by simo5** [comment]
What does `pkgconf --variable=modulesdir libcrypto` return on the build system?

**Comment by simo5** [comment]
It should return /usr/lib64/ossl-modules which is the installation path for modules, of couse that directory needs to be writable to actually install something in it.

**Comment by numinit** [comment]
It returns /nix/store/8bdd933v69w05k5v8hfcq74bi1f9545k-openssl-3.0.13/lib/ossl-modules, which is the path for OpenSSL in nixpkgs.

**Comment by simo5** [comment]
then you'll need that to be writable, you are building a module for openssl, it needs to be placed where openssl can find it. Find other programs that have externally contributed plugins and see how nixpkgs handles it, this is not a pkcs11-provider issue, and the previous build system was doing that same thing.

**Comment by numinit** [comment]
The point is that it can't be writable and we need to install it in a unique directory. We tend to install things to unique paths in nixpkgs and compose them together with symlinks.

**Comment by simo5** [comment]
As I said, that is the path where openssl looks for modules, ask the openssl package maintainer for guidance on what to do I guess?
