### ISSUE TITLE
Fallback to fetching public key from certificate not always applied?

### ISSUE THREAD

**Issue by selvanair** [latchset/pkcs11-provider#430]
(moving this from a comment on a closed issue to a new thread)
Request: Make the fallback to fetching public key from certificate work with OpenSSL's SSL_CTX_use_Privatekey().

This fallback was apparently implemented by #129 but that does not seem to work when an EC private key is passed to `SSL_CTX_use_Privatekey()` in OpenSSL even if matching certificate is present with same ID. In this case `p11prov_ec_match()` gets called which fails to find the public key via `find_associated_obj()`. Would be nice to get the fallback applied here too for wider usability. 

Whereas, when signing using "openssl pkeyutl" the fallback does work and appears to follow a different code path.

Tested using git master branch and a soft token (softhsm2) where only private key (EC) and certificate were imported into the token using `p11tool` -- public key was not explicitly imported. The same token works with `pkcs11-helper` library. 

Unlike `p11tool`, `softhsm2-util` imports keypair in one step and creates both public and private key objects in the token --- in that case there are no such errors, obviously.

**Comment by simo5** [comment]
Can you describe what "here too" means ?
Can you provide a reproducer to understand what does not work, and in what situation ?

**Comment by Jakuje** [comment]
I am considering the tokens without separate public key objects hard to universally support, especially in case of ECC where the private key object does not contain the public counterpart. Even though the applications and libraries can try to oustmart this by parsing the public key from the certificate, I think there will always be some applications that will not know how to handle this and its likely better to make sure the public object is present.

That said, I do not think we should not implement this, but I do not think it has high priority. I wanted to look into this with some reproducer, but did not get into that yet. But reproducer would be either to generate keys outside of the token and import only private key + cert or after standard key generation step, remove the public key object.

**Comment by Jakuje** [comment]
Actually, this test was written already year ago in #213 and still runs for both RSA and ECDSA keys (except for Mac where it was crashing with p11-kit, which we no longer use. Let me see if it is still the case.

Please, let us know what was your setup, where this did not work.

**Comment by selvanair** [comment]
What does not work is setting an EC certificate and key in an SSL context using OpenSSL API in C. In short this involves two steps (see below for a full test program):
(i) fetch a certificate and private key using OpenSSL STORE API and a `pkcs11:` URI with `pkcs11-provider` loaded. 
(ii) set the certificate and the key in an SSL context. The latter (i.e., setting the key) fails when public key is not on the token, succeeds otherwise.

[Here](https://gist.github.com/selvanair/ebe0263cd52b501be2031aa316d5cf7d) is a sample program that demonstrates this. I tested it using a soft token (softhsm2) which contains a single key and cert imported with the same id = 01 so that the URI used is hard-coded as simply: "pkcs11:id=01".

OpenSSL error:
```
4037945B88740000:error:40800000:pkcs11:find_associated_obj:pkcs11:../src/objects.c:1136:Error in C_FindObjects (count=0)
4037945B88740000:error:40800005:pkcs11:match_public_keys:General Error:../src/objects.c:2314:Could not find associated public key object
4037945B88740000:error:05800074:x509 certificate routines:X509_check_private_key:key values mismatch:../crypto/x509/x509_cmp.c:405:
```

pkcs11-provider debug output just before the above error:
```
[../src/keymgmt.c:1343] p11prov_ec_has(): ec has 0x5f1ebfae75c0 2
[../src/keymgmt.c:1254] p11prov_ec_new(): ec new
[../src/keymgmt.c:1377] p11prov_ec_import(): ec import 0x5f1ebfaf1980
[../src/keymgmt.c:1365] p11prov_ec_match(): ec match 0x5f1ebfaf1980 0x5f1ebfae75c0 6
[../src/objects.c:1096] find_associated_obj(): Find associated object
[../src/session.c:867] p11prov_get_session(): Get session on slot 1844729915, reqlogin=true, rw=false
[../src/session.c:876] p11prov_get_session(): single-shot request for slot 1844729915
[../src/session.c:596] check_slot(): Checking Slot id=1844729915, uri=(nil), mechtype=ffffffffffffffff, rw=false)
[../src/provider.c:595] p11prov_ctx_login_behavior(): login_behavior = 0
[../src/interface.gen.c:305] p11prov_GetSessionInfo(): Calling C_GetSessionInfo
[../src/interface.gen.c:305] p11prov_GetSessionInfo(): Calling C_GetSessionInfo
[../src/interface.gen.c:533] p11prov_FindObjectsInit(): Calling C_FindObjectsInit
[../src/interface.gen.c:559] p11prov_FindObjects(): Calling C_FindObjects
[../src/interface.gen.c:583] p11prov_FindObjectsFinal(): Calling C_FindObjectsFinal
[../src/objects.c:1136] find_associated_obj(): Error: 0x00000000; Error in C_FindObjects (count=0)
[../src/objects.c:2314] match_public_keys(): Error: 0x00000005; Could not find associated public key object
```

So it appears `p11prov_ec_match()` fails in `find_associated_obj()` called from `match_public_keys()`.

**Comment by simo5** [comment]
Thanks for the bug report, #435 should fix it as requested.
