### ISSUE TITLE
Installation breaks NetworkManager connection to WPA2-Enterprise networks

### ISSUE THREAD

**Issue by makinbacon21** [latchset/pkcs11-provider#467]
**Describe the bug**
I routinely connect to an `eduroam` network using WPA2-Enterprise with PEAP and MSCHAPV2. I run Fedora 41. Recently, this package was updated for Fedora 41 and completely broke my ability to authenticate. No clue why, but uninstalling this ( https://discussion.fedoraproject.org/t/unable-to-connect-to-wpa2-enterprise-after-upgrading-to-fedora-41/134889/33 ) for more details.

**To Reproduce**
1. Update to F41 `pkcs11-provider` (0.5-3.fc41)
2. Try to connect

**Expected behavior**
Self-explanatory.

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version: 41

**Token and application used (please complete the following information):**
 - Device: Framework 16 AMD
 - PKCS11 Driver version: 1.30.0-2.fc41 (?)

**Comment by simo5** [comment]
It is still a fedora specific bug, in fedora we changed the RPM package to load pkcs11-provider by default, dissenting when the upstream *and* Fedora maintainer tells you to file bugs first in Fedora, is arrogant, please be better!
