### ISSUE TITLE
pkcs11-provider with yubikey token

### ISSUE THREAD

**Issue by simo5** [latchset/pkcs11-provider#88]
### Discussed in https://github.com/latchset/pkcs11-provider/discussions/83

<div type='discussions-op-text'>

<sup>Originally posted by **gilweis** November  4, 2022</sup>
Hi,
I am trying to check the library with yubikey token.

OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
latest pkcs11-provider library
pkcs11 module: /usr/lib/x86_64-linux-gnu/libykcs11.so
key-type: "rsa:2048"

The operation of reading the public key is ok:
$ **openssl pkey -in "pkcs11:type=public;id=%02" -pubin -pubout -out testkey2.pub** 

The operation with private key fails:
$ **openssl req -new -batch -key "pkcs11:type=private;id=%02" -out tmp.csr**

_Error making certificate request
4007D721007F0000:error:0580006F:x509 certificate routines:X509_PUBKEY_set:unsupported algorithm:../crypto/x509/x_pubkey.c:359:_
</div>

**Comment by gilweis** [comment]
OpenSSL 3.0.10 1 Aug 2023 (Library: OpenSSL 3.0.10 1 Aug 2023)
latest pkcs11-provider library
pkcs11 module: /usr/lib/x86_64-linux-gnu/libykcs11.so

$ openssl pkey -in "pkcs11:type=public;id=%02" -pubin -pubout -out testkey2.pub

Enter pass phrase for PKCS#11 Token (Slot 0 - Yubico YubiKey CCID 00 00):
Could not read key of Public Key from pkcs11:type=public;id=%02

(make check is ok)

**Comment by simo5** [comment]
can you run 'openssl storeutl -text pkcs11:type=public;id=%02' and post the results?

**Comment by dengert** [comment]
Are you using the PIV or the OpenPGP applet on the Yubikey? 
libykcs11.so only supports the PIV applet via PKCS11. 

You can use the OpenSC pkcs11 with the openpgp applet but see:
https://github.com/OpenSC/OpenSC/discussions/2937#discussioncomment-7599413
